[package]
name = "boltay-translate"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
boltay-text = { path = "../boltay-text" }
num_cpus = "1.17"
ort = { version = "=2.0.0-rc.13", default-features = false, features = ["std", "download-binaries", "copy-dylibs", "tls-native"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokenizers = { version = "0.22", default-features = false, features = ["fancy-regex"] }
